import hashlib
import os
import secrets
import sys
import uuid
from datetime import datetime, timedelta, timezone
from typing import Optional

import anyio
from fastapi import APIRouter, HTTPException, Request, Response
from pydantic import BaseModel

from src.auth import (
    create_access_token,
    decode_access_token,
    SESSION_MAX_DAYS,
)
from src.database.db import get_db_cursor
from src.logger import logging

router = APIRouter(prefix="/api/auth", tags=["Authentication"])


class VerifyKeyRequest(BaseModel):
    api_key: str


@router.post("/verify-key")
async def verify_key(body: VerifyKeyRequest, response: Response):
    """Validates an API key generated by seed_user.py."""
    key = body.api_key.strip() if body.api_key else ""
    if not key:
        return {"valid": False, "message": "Please enter an API key."}
    if key == "guest":
        token = create_access_token(
            user_id="00000000-0000-0000-0000-000000000001",
            session_id=str(uuid.uuid4()),
            email="guest@docuvortex.local",
            username="guest",
        )
        response.set_cookie(
            key="access_token",
            value=token,
            httponly=True,
            samesite="lax",
            secure=False,
            max_age=SESSION_MAX_DAYS * 86400,
            path="/",
        )
        return {
            "valid": True,
            "user": {
                "id": "00000000-0000-0000-0000-000000000001",
                "username": "guest",
                "email": "guest@docuvortex.local",
            },
        }

    key_hash = hashlib.sha256(key.encode()).hexdigest()
    try:
        with get_db_cursor(commit=False) as cur:
            cur.execute(
                "SELECT id, username, email FROM users WHERE api_key_hash = %s LIMIT 1",
                (key_hash,),
            )
            row = cur.fetchone()
            if row:
                user_id = str(row["id"])
                username = row.get("username") or "User"
                email = row.get("email") or ""
                last_session_id = None
                try:
                    cur.execute(
                        """
                        SELECT session_id
                        FROM sessions
                        WHERE user_id = %s
                        ORDER BY updated_at DESC
                        LIMIT 1
                        """,
                        (user_id,),
                    )
                    last_row = cur.fetchone()
                    if last_row:
                        last_session_id = last_row["session_id"]
                except Exception as sess_err:
                    logging.debug("verify-key session fetch note: %s", sess_err)

                token = create_access_token(
                    user_id=user_id,
                    session_id=str(uuid.uuid4()),
                    email=email,
                    username=username,
                )
                response.set_cookie(
                    key="access_token",
                    value=token,
                    httponly=True,
                    samesite="lax",
                    secure=False,
                    max_age=SESSION_MAX_DAYS * 86400,
                    path="/",
                )

                return {
                    "valid": True,
                    "user": {
                        "id": user_id,
                        "username": username,
                        "email": email,
                    },
                    "last_session_id": last_session_id,
                }
    except Exception as e:
        logging.warning("verify-key error: %s", e)

    return {
        "valid": False,
        "message": "Invalid API key. Please check the key generated with seed_user.py.",
    }


@router.get("/session-status")
async def session_status(request: Request):
    user_id = None
    username = None
    email = None
    last_session_id = None

    # 1. Check API Key header or query param (Primary authentication via seed_user.py)
    api_key = (
        request.headers.get("X-API-Key")
        or request.query_params.get("api_key")
        or ""
    ).strip()

    if api_key and api_key != "guest":
        key_hash = hashlib.sha256(api_key.encode()).hexdigest()
        try:
            with get_db_cursor(commit=False) as cur:
                cur.execute(
                    "SELECT id, username, email FROM users WHERE api_key_hash = %s LIMIT 1",
                    (key_hash,),
                )
                row = cur.fetchone()
                if row:
                    user_id = str(row["id"])
                    username = row.get("username") or "User"
                    email = row.get("email") or ""
        except Exception as e:
            logging.debug("session-status API key check note: %s", e)
    elif api_key == "guest":
        user_id = "00000000-0000-0000-0000-000000000001"
        username = "guest"
        email = "guest@docuvortex.local"

    # 2. Check Cookie fallback
    if not user_id:
        token = request.cookies.get("access_token")
        if token:
            payload = decode_access_token(token)
            if payload and "sub" in payload:
                user_id = payload["sub"]
                username = payload.get("username") or (payload.get("email", "User").split("@")[0] if payload.get("email") else "User")
                email = payload.get("email", "")

    if not user_id:
        return {"authenticated": False}

    try:
        with get_db_cursor(commit=False) as cur:
            cur.execute(
                "SELECT username, email FROM users WHERE id = %s LIMIT 1",
                (user_id,),
            )
            row = cur.fetchone()
            if row:
                username = row.get("username") or username
                email = row.get("email") or email

            # Find the user's most recently active chat session
            cur.execute(
                """
                SELECT s.session_id
                FROM sessions s
                WHERE s.user_id = %s
                ORDER BY s.updated_at DESC
                LIMIT 1
                """,
                (user_id,),
            )
            last_row = cur.fetchone()
            if last_row:
                last_session_id = last_row["session_id"]
    except Exception as e:
        logging.debug("session-status DB check note: %s", e)

    return {
        "authenticated": True,
        "user": {
            "id": user_id,
            "username": username,
            "email": email,
        },
        "last_session_id": last_session_id,
    }


@router.post("/logout")
async def logout(request: Request, response: Response):
    token = request.cookies.get("access_token")
    if token:
        payload = decode_access_token(token)
        if payload and payload.get("session_id"):
            try:
                with get_db_cursor(commit=True) as cur:
                    cur.execute("DELETE FROM user_sessions WHERE id = %s", (payload["session_id"],))
            except Exception as e:
                logging.debug("Logout session cleanup note: %s", e)

    response.delete_cookie(key="access_token", path="/")
    return {"success": True, "message": "Logged out successfully", "redirect": "/"}
